version: '3'

services:

  nodejs:
    build:
      context: ./backend
      dockerfile: Dockerfile
      target: base
    container_name: students_node
    restart: unless-stopped
    env_file:
      - .env
    environment:
      - DATABASE_URL
      - NODE_ENV
    ports:
      - "80:3000"
    volumes:
      - ./backend:/usr/src/app
      - ./backend/node_modules:/usr/src/app/node_modules
    # depends_on:
    #   db:
    #     condition: service_started
    networks:
      - app-network
    command: npm run dev

  # db:
  #   image: postgres:14
  #   container_name: ppz_db
  #   restart: unless-stopped
  #   env_file: .env
  #   environment:
  #     - POSTGRES_USER
  #     - POSTGRES_PASSWORD
  #   volumes:
  #     - ./database/scripts:/docker-entrypoint-initdb.d/
  #   networks:
  #     - app-network
  #   ports:
  #     - "5431:5432"

networks:
  app-network:
    driver: bridge