version: '3'

services:

  nodejs:
    command: npm test

  db:
    image: mysql
    container_name: students_db
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    env_file:
      - .env
    environment:
      - MYSQL_ROOT_PASSWORD
      - MYSQL_DATABASE
      - MYSQL_USER
      - MYSQL_PASSWORD
      - MYSQL_HOST
    networks:
      - app-network
    ports:
      - "3307:3306"

networks:
  app-network:
    driver: bridge