version: '3'

services:

  nodejs:
    build:
      context: ./backend
      dockerfile: Dockerfile
      target: production
    command: node build/index.js

networks:
  app-network:
    driver: bridge