version: '3'

services:

  nodejs:
    command: npm test

  db:
    image: postgres:14
    container_name: students_db
    restart: unless-stopped
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=student
      - POSTGRES_DB=education
    networks:
      - app-network
    ports:
      - "5431:5432"

networks:
  app-network:
    driver: bridge